config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :users
  resources :atlases
  resources :atlas_pages
  resources :locations do
    resources :private_notes
  end
  resources :location_atlas_page_relationships

  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'  
  delete 'signout' => 'sessions#destroy'
end

app/controllers/atlases_controller.rb
class AtlasesController < ApplicationController

  before_filter :require_current_user
  before_filter :require_owner

  def show
    @atlas = Atlas.find( params[:id] )
  end

  def index
    if logged_in?
      redirect_to @current_user.atlas
    else
      redirect_to signin_path
    end
  end

private

  # Can use @current_user here because the require_current_user before_filter will make sure they exist
  def require_owner
    @atlas = Atlas.find(params[:id])
    if !@atlas.owned_by?(@current_user )
      flash[:error] = "You can only view your own atlas"
      redirect_to @current_user.atlas
    end
  end

end

app/views/atlases/_map.html.erb
<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'atlas-map'}}, function(){
  markers = handler.addMarkers( <%= get_markers( @atlas ).html_safe %> );
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/atlases/show.html.erb
<h1><%= @atlas.user.username %>'s Atlas</h1>
<h4>Atlas Pages</h4>
<% @atlas.atlas_pages.each do |ap| %>
  <div><%= link_to ap.name, ap %> | <%= ap.description %></div>
<% end %>

<div class="map-container">
  <div id="atlas-map"></div>
</div>

<%= link_to "New Atlas Page", new_atlas_page_path, :class => "btn-success btn", :style => "margin-top: 30px;" %>

<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<%= render 'map' %>