config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :users
  resources :atlases
  resources :atlas_pages
  resources :locations do
    resources :private_notes
  end
  resources :location_atlas_page_relationships

  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'  
  delete 'signout' => 'sessions#destroy'
end

app/models/atlas_page.rb
class AtlasPage < ActiveRecord::Base
  validates :name, :presence => true, :length => {:maximum => 25}
  before_create :assign_color_code

  belongs_to :atlas
  has_many :location_atlas_page_relationships
  has_many :locations, :through => :location_atlas_page_relationships

  # RDEBUG: Test these

  def owner
    self.atlas.user
  end

  def owned_by?( user )
    owner == user
  end

  def public?
    self.public
  end

  # If public is somehow not set, mark page private
  def private?
    self.public || true
  end

  def can_be_read_by?( user )
    return (self.public || self.owned_by?(user))
  end

  def make_private!
    self.public = false
    self.save
  end

  def make_public!
    self.public = true
    self.save
  end

  def assign_color_code
    self.color_code = "%06x" % (rand * 0xffffff)
  end

end

app/controllers/atlas_pages_controller.rb
class AtlasPagesController < ApplicationController

  before_action :ensure_user, :only => [:edit, :update, :destroy]
  before_action :ensure_viewable, :only => :show

  def new
    @atlas_page = AtlasPage.new
  end

  def create
    @atlas_page = AtlasPage.new( atlas_page_params )
    if @atlas_page.valid?
      @current_user.atlas.atlas_pages.create( atlas_page_params )
      flash[:success] = "Atlas page #{params[:atlas_page][:name]} created successfully"
      redirect_to @current_user.atlas
    else
      flash[:error] = @atlas_page.errors.full_messages
      render 'new'
    end
  end

  def edit
    @atlas_page = AtlasPage.find(params[:id])
  end

  def update
    @atlas_page = AtlasPage.find(params[:id])
    if @atlas_page.update_attributes( atlas_page_params )
      flash[:success] = "Atlas page #{params[:atlas_page][:name]} updated successfully"
      redirect_to @atlas_page
    else
      flash.now[:error] = @atlas_page.errors.full_messages
      render 'edit'
    end    
  end

  def show
    @atlas_page = AtlasPage.find(params[:id])
  end

  def destroy

  end

  private
    def atlas_page_params
      params.require(:atlas_page).permit(:name,:description)
    end

    def ensure_user
      @atlas_page = AtlasPage.find(params[:id])
      return false if !(@atlas_page.owner == @current_user)
    end

    def ensure_viewable
      @atlas_page = AtlasPage.find(params[:id])
      if !@atlas_page.can_be_read_by?( @current_user )
        flash[:error] = "You don't have permission to view that atlas page"
        redirect_to root_path
      end
    end
end

app/helpers/atlas_page_helper.rb
module AtlasPageHelper

  # Just add a hex color code to the end to get a pin of that color
  GOOGLE_MAPS_PIN_URL = "http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|"

  def get_markers_for_page( atlas_page )
    markers = []
    atlas_page.locations.each do |loc|
      markers << {"lat": loc.latitude, "lng": loc.longitude,
                  "picture": {"url": GOOGLE_MAPS_PIN_URL + atlas_page.color_code,
                              "width": 32, "height": 32},
                  "infoWindow": loc.name + "\n" + loc.address}
    end
    markers
  end

  def get_markers( atlas )
    markers = []
    atlas.atlas_pages.each do |ap|
      get_markers_for_page( ap ).each do |marker|
        markers << marker
      end
    end
    logger.debug( "RDEBUG: " +  markers.to_json )
    markers.to_json
  end

end

app/views/atlas_pages/_form.html.erb
<%= form_for @atlas_page do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, :class => "form-control" %>
  </div>
  <%= f.submit action_name.capitalize + " Atlas Page", :class => "btn" %>
<% end %>

app/views/atlas_pages/edit.html.erb
<h1>Edit Atlas Page</h1>
<%= render 'form' %>

app/views/atlas_pages/new.html.erb
<h1>New Atlas Page</h1>
<%= render 'form' %>

app/views/atlas_pages/show.html.erb
<h1><%= @atlas_page.name %></h1>
<h2><%= @atlas_page.description %></h2>
<h4>Locations</h4>
<ul>
<% @atlas_page.locations.each do |loc| %>
  <li><%= link_to loc.name, loc %> |
      <% if @current_user %>
        <% if location_private_notes(loc, @current_user).count > 0 %>
          <%= link_to "#{location_private_notes(loc, @current_user).count} notes", location_private_notes_path( :location_id => loc.id ) %>
        <% else %>
          <%= location_private_notes(loc, @current_user).count %> notes
        <% end %>
      <% end %>
  </li>
<% end %>
</ul>

<% if @current_user %>
  <% if @atlas_page.owned_by? @current_user %>
    <%= link_to "Back to atlas", @atlas_page.atlas %>
  <% else %>
    <p>TODO: Add menu to copy atlas page to current_user's atlas</p>
  <% end %>
<% end %>