config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :users
  resources :atlases
  resources :atlas_pages
  resources :locations do
    resources :private_notes
  end
  resources :location_atlas_page_relationships

  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'  
  delete 'signout' => 'sessions#destroy'
end

app/models/location.rb
class Location < ActiveRecord::Base
  geocoded_by :address
  validates :name, :presence => true, :length => {:maximum => 75}
  validates :address, :presence => true
  after_validation :geocode, if: ->(location){ location.address.present? and location.address_changed? }

  has_many :location_atlas_page_relationships
  has_many :atlas_pages, :through => :location_atlas_page_relationships
  has_many :private_notes
  has_many :public_tips

  def add_to_atlas_page( atlas_page_id )
    page = AtlasPage.find( atlas_page_id )
    self.atlas_pages.push( page )
  end

  def notes_by( user )
    self.private_notes.where( user: user )
  end

  def contained_in_user_atlas_pages( user )
    user.atlas.atlas_pages.select{|ap| ap.locations.include?( self ) }
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def new
    @location = Location.new
  end

  def create
    @location = Location.new( location_params )
    if @location.save
      flash[:success] = "Successfully created location '#{@location.name}'"
      redirect_to @location
    else
      flash[:error] = @location.errors.full_messages
      render 'new'
    end
  end

  def show
    @location = Location.find( params[:id] )
  end

  def index
    if params[:query]
      @locations = Location.near(params[:query],5)
    else
      @locations = Location.all
    end
  end

  def edit
    @location = Location.find( params[:id] )
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes( location_params )
      flash[:success] = "Successfully updated '#{@location.name}'"
      redirect_to @location
    else
      flash[:error] = @location.errors.full_messages
      render 'edit'
    end
  end

  private

  def location_params
    params.require(:location).permit(:name, :address)
  end

end

app/views/locations/_add_to_atlas_page.html.erb
<div class="modal fade" id="addToAtlasPageModal" role="dialog" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="vertical-alignment-helper">
  <div class="modal-dialog vertical-align-center">
  <div class="modal-content">
  <%= form_for @location.location_atlas_page_relationships.new(:location_id => @location.id), :remote => true do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Add to Atlas Page</h3>
  </div>
  <div class="modal-body">
<!-- RDEBUG: Need to remove the option to add to atlas pages that already contain this location -->
      <div><%= f.select :atlas_page_id, options_from_collection_for_select(@current_user.atlas_pages, :id, :name) %></div>
      <div><%= f.hidden_field :location_id %></div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <%= f.submit "Add to Atlas Page", :class => "btn btn-success" %>
  </div>
  <% end %>
  </div>
  </div>
  </div>
</div>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, :class => "form-control" %>
  </div>

  <%= f.submit "Submit", :class => "btn btn-submit" %>

<% end %>

app/views/locations/_list_atlas_pages.html.erb
  <% @location.contained_in_user_atlas_pages( @current_user ).each do |ap| %>
    <div><%= link_to ap.name, ap %> - <%= ap.description %> | Remove</div>
  <% end %>

app/views/locations/edit.html.erb
<h1>Edit Location</h1>
<%= render 'form' %>

app/views/locations/index.html.erb
<% @locations.all.each do |loc| %>
  <%= link_to loc.name, loc %><br />
<% end %>

<%= link_to "Create New Location", new_location_path, :class => "btn btn-info", :style => "margin-top: 30px" %>

app/views/locations/new.html.erb
<h3>Create New Loation</h3>
<%= render 'form' %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>
<h2 style="margin-top:-30px;"><%= @location.address %></h2>
<p>TODO: Add logo and categories</p>

<% if @current_user %>

<div style="margin-top:30px;">
  <h3>Private Notes</h3>
  <% @location.notes_by(@current_user).each do |pn| %>
    <p>- <%= pn.text %></p>
    <p>TODO: Add a button to delete/edit private note</p>
  <% end %>

  <%= link_to "Add a private note", new_location_private_note_path(:location_id => @location.id)%>
</div>

<h3>In My Atlas Pages</h3>
<div id="in-atlas-pages">
  <%= render 'list_atlas_pages' %>
</div>
<div style="margin-top:7px">
  <%= link_to "Add to Atlas Page", "#addToAtlasPageModal", :class => "btn btn-primary", "data-toggle" => "modal" %>
</div>
<%= render 'add_to_atlas_page' %>

<p>TODO: Add to Atlas Page button, select from existing pages, create new page</p>


<% end %>

<h3>In Atlas Pages</h3>
<p>TODO: List popular atlas pages that contain this location</p>