config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :users
  resources :atlases
  resources :atlas_pages
  resources :locations do
    resources :private_notes
  end
  resources :location_atlas_page_relationships

  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'  
  delete 'signout' => 'sessions#destroy'
end

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
	<% if logged_in? %>
          <%= link_to "Odyssey", current_user.atlas, id: "logo" %>
	<% else %>
	  <%= link_to "Odyssey", root_path %>
	<% end %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
            <li><%= link_to "My Atlas", current_user.atlas %></li>
            <li><%= link_to "Locations", locations_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", "#" %></li>
                <li><%= link_to "My Atlas", current_user.atlas %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
            <% else %>
              <li><%= link_to "Log in", signin_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>